### GET / 
GET http://localhost:5003 


###Register a user POST /auth/regiter 
POST http://localhost:5003/auth/register 
Content-Type: application/json 

{
    "username" : "Nhan@gmail.com", 
    "password" : "123456"
}

###Login a user POST /auth/login 
POST http://localhost:5003/auth/login 
Content-Type: application/json 

{
    "username" : "Nhan@gmail.com",   
    "password" : "123456"
}

### Fetch all todos GET /todos (protected by token) 
GET http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3MjQ3MTIyLCJleHAiOjE3NDczMzM1MjJ9.FtMVFQRYuXWGjN6tvSVr-6jnD6VcgO2dnFeKacVVQms


###Creates a new todo POST /todos (protected)
POST http://localhost:5003/todos 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3MjQ3MTIyLCJleHAiOjE3NDczMzM1MjJ9.FtMVFQRYuXWGjN6tvSVr-6jnD6VcgO2dnFeKacVVQms
Content-Type: application/json  

{
    "task" : "finish coding project" 
}

###update a todo PUT /todos/:id (protected) 
PUT http://localhost:5003/todos/2 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3MjQ3MTIyLCJleHAiOjE3NDczMzM1MjJ9.FtMVFQRYuXWGjN6tvSVr-6jnD6VcgO2dnFeKacVVQms
Content-Type: application/json 

{
    "completed" : 1 
}

###Delete a todo DELETE /todos/:id (protected) 
DELETE http://localhost:5003/todos/3 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ3MjQ3MTIyLCJleHAiOjE3NDczMzM1MjJ9.FtMVFQRYuXWGjN6tvSVr-6jnD6VcgO2dnFeKacVVQms
